<?php

namespace AppBundle\Repository;

/**
 * ProductDetailEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDetailEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
