<?php

namespace AppBundle\Repository;

/**
 * ProductEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
