# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    app.leboncoin:
        class: AppBundle\Services\Leboncoin
        arguments: ['@doctrine.orm.entity_manager']